### ISSUE TITLE
Android Error: getAdSize must be called on the main UI thread.

### ISSUE THREAD

**Issue by letsbelopez** [rdlabo/capacitor-admob#10]
Getting this error in Android for a banner ad.

I'm calling showBanner and hideBanner on a couple ionViewWillEnter and ionViewWillLeave functions.

```
{"arguments":["Unhandled Promise rejection:",{"message":"getAdSize must be called on the main UI thread."},"; Zone:","<root>","; Task:",null,"; Value:",{"message":"getAdSize must be called on the main UI thread."},"[undefined]"]}
```

**Comment by rdlabo** [comment]
`showBanner()` can use once. Please use `resumeBanner()` after `hideBanner()` .

**Comment by letsbelopez** [comment]
This is for getAdSize happening in resumeBanner not showBanner

```
    java.lang.IllegalStateException: getAdSize must be called on the main UI thread.
        at wi.b(:com.google.android.gms.dynamite_adsdynamite@16089052@16.0.89 (040700-239467275):10)
        at com.google.android.gms.ads.nonagon.shim.h.c(:com.google.android.gms.dynamite_adsdynamite@16089052@16.0.89 (040700-239467275):68)
        at com.google.android.gms.ads.nonagon.shim.j.c(:com.google.android.gms.dynamite_adsdynamite@16089052@16.0.89 (040700-239467275):16)
        at com.google.android.gms.ads.internal.client.an.a(:com.google.android.gms.dynamite_adsdynamite@16089052@16.0.89 (040700-239467275):122)
        at oi.onTransact(:com.google.android.gms.dynamite_adsdynamite@16089052@16.0.89 (040700-239467275):4)
        at android.os.Binder.transact(Binder.java:499)
        at com.google.android.gms.internal.ads.zzfm.transactAndReadException(Unknown Source)
        at com.google.android.gms.internal.ads.zzzk.zzpn(Unknown Source)
        at com.google.android.gms.internal.ads.zzaaz.getAdSize(Unknown Source)
        at com.google.android.gms.ads.BaseAdView.getAdSize(Unknown Source)
        at com.google.android.gms.ads.AdView.getAdSize(Unknown Source)
        at jp.rdlabo.capacitor.plugin.admob.AdMob.resumeBanner(AdMob.java:243)  <----- here
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:520)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by dicoriomri** [comment]
any news or solution about this?
