### ISSUE TITLE
BannerAd doesn't show in Android

### ISSUE THREAD

**Issue by it-one-mm** [rdlabo/capacitor-admob#3]
I use this code in Ionic React Class Component

 ```
async componentDidMount() {
    if (isPlatform('android') || isPlatform('ios'))
      await this.showBanner();
  }

`showBanner = async () => {
    const options: AdOptions = {
      adId: BANNER_AD_ID,
      adSize: AdSize.SMART_BANNER,
      position: AdPosition.BOTTOM_CENTER,
    };

    await AdMob.showBanner(options);
  }`
```

**Comment by adeoy** [comment]
Im have the same problem. In the console says that its loads fine, and if I touch the bottom of the screen the ad opens, but I cant see it.

**Comment by bonny** [comment]
Same problem here. The banner is visible when I run my app in the emulator but not on a real device.

Not sure if this is the reason, but I do get this message on the real device but not in the emulator:

```
2020-01-12 17:22:46.547 21035-21134/com.mufflify.TextTVnu E/Capacitor/Plugin: The ad size can only be set once on AdView.
    java.lang.IllegalStateException: The ad size can only be set once on AdView.
        at com.google.android.gms.internal.ads.zzaaz.setAdSizes(Unknown Source:162)
        at com.google.android.gms.ads.BaseAdView.setAdSize(Unknown Source:32)
        at com.google.android.gms.ads.AdView.setAdSize(Unknown Source:13)
        at jp.rdlabo.capacitor.plugin.admob.AdMob.showBanner(AdMob.java:99)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$2.run(Bridge.java:537)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by rdlabo** [comment]
@it-one-mm @adeoy @bonny Can you share repository?? It looks that do before initialize() or run multiple times.
Thanks.

**Comment by bonny** [comment]
> @it-one-mm @adeoy @bonny Can you share repository?? It looks that do before initialize() or run multiple times.
> Thanks.

Yes, my repo is here:
https://github.com/bonny/texttv.nu/tree/texttv2019

**Comment by rdlabo** [comment]
@bonny This repository is worked well in my environment. Please re-install node_modules.

![スクリーンショット 2020-01-16 21 56 00](https://user-images.githubusercontent.com/9690024/72526992-0f91d500-38ab-11ea-8e89-5b92872dc93c.png)

**Comment by bonny** [comment]
> @bonny This repository is worked well in my environment. Please re-install node_modules.
> 
> ![スクリーンショット 2020-01-16 21 56 00](https://user-images.githubusercontent.com/9690024/72526992-0f91d500-38ab-11ea-8e89-5b92872dc93c.png)

Thanks for testing rdlabo. The banner does work for me too in the emulator, it's on a real android phone where it does not show.

I will however try to clean node modules and try on a real device again.

**Comment by adeoy** [comment]
> @it-one-mm @adeoy @bonny Can you share repository?? It looks that do before initialize() or run multiple times.
> Thanks.

Where do you initialize the Ad? Do you have a simple React example? Thanks.

**Comment by rdlabo** [comment]
I will close this issue because nobody else shares the code. Thanks.
